### ISSUE TITLE
Mobile App: Fix Enter OTP view and Implement new UI

### ISSUE THREAD

**Issue by gianalarcon** [Quantum3-Labs/themarquis-app#1]
## Issue Overview

1. Views for Home page, user profile and Signup/Login sections are outdated.

2. Currently if we try to remove/delete the entered OTP, we have to select box by box. 
![image](https://github.com/user-attachments/assets/bc31946a-96ac-4790-a097-1f38e232cfbe)

3. Current implementation of Invite friend to signup is missing `Save image` feature.

## Proposed Solutions or Ideas

1. Implement/Update views for Home page, user profile and Signup/Login section. [here](https://www.figma.com/design/Zwa4tGNPAfPgAkDZtQrNLa/marquis-mobile?node-id=0-1&node-type=canvas&t=M2aEz9laY0Me077q-0). New UI shouldn't break current functionality

2. Fix it in order to touch the backspace symbol then it should clean the box and move to the next one

3. Implement [Save image](https://www.figma.com/design/Zwa4tGNPAfPgAkDZtQrNLa/marquis-mobile?node-id=2-16277&node-type=frame&t=M2aEz9laY0Me077q-0) feature based on design.

**Comment by 0xdevcollins** [comment]
Can I take this issue?

**Comment by Hoossayn** [comment]
Hi @gianalarcon, I'd like to work on this

**Comment by Kingsuite** [comment]
Can I take care of this issue?

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/
May I try this one?

**Comment by Supa-mega** [comment]
Could I be assigned to this?

**Comment by Benjtalkshow** [comment]
I'd like to take this issue.

**Comment by ShantelPeters** [comment]
Mind if I take this issue please?

**Comment by Michaelkingsdev** [comment]
I'd like to take this issue.

**Comment by gianalarcon** [comment]
all yours @Hoossayn. Remember that you have to create your branch based on our develop branch and your PR should point to our develop branch. Not our main branch

**Comment by gianalarcon** [comment]
closed with #6
