### ISSUE TITLE
Mobile app: Fix and Improve current develop branch

### ISSUE THREAD

**Issue by gianalarcon** [Quantum3-Labs/themarquis-app#18]
## Issue Overview

- There has been many PRs that got merged, need to re-conciliate them with main branch
- The loading indicator is on top/ inside the cyan blue button, which it should replace the button, rather than overlap it
- The appbar in game screen is missing.
- The wording of "No tokens available..... start!" is too small to read.
- The waiting room not updated when user join (current user changes not reflected). The bottom start button is changing, but the last user box pic is still empty
- The menu screen background display got problem, seems the overlay scaling problem. It is displaying a enlarged version of the board when I return from the game to the Game Menu Screen.
- 
The dice rolling animation, after roll dice no stop and show the rolled value

## Proposed Solutions or Ideas

- Clean,fix,  integrate and test whole gameplay.
- Check missing relevant edge cases.

**Comment by Emrys02** [comment]
Hey @gianalarcon, 
I'd like to pick this up.

### Plans To Solve The Issue
1.  ***Resolve overflow issues*** if any instance of it occurs
2.  ***Address other UI bugs*** like the loading indicator, and enlarged background image on the menu screen.
3.  ***Introduce missing UI elements*** like the appbar on game screen and others identified after reviewing the design.
4. ***Run user test*** to identify other UI issues and overlooked bugs

**Comment by Supa-mega** [comment]
Would love to tackle this!

**Comment by tasneemtoolba** [comment]
can I take this issue? I'm already familiar with the code, errors/bugs in both desgin or logic!!

**Comment by raizo07** [comment]
May I take care of this? I'm a Software developer with over 3 years experience

**Comment by akintewe** [comment]
Hello i am a flutter developer and would love to work on these fixes on   the app i am very  familiar with the codebase and would love to work more on it ;) ETA 48 hours

**Comment by tasneemtoolba** [comment]
Let me try this one! I'm already familiar with the code base and both design and logic errors/corner cases!

**Comment by akintewe** [comment]
Hello i am a flutter developer and would like to work on this issue once more, thank you for this opportunity :) ETA 48 hours

**Comment by jedstroke** [comment]
Can I take this from here?

**Comment by Jagadeeshftw** [comment]
Hi,
I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Hi,  

I’d be thrilled to work on this issue as I have extensive experience with Cairo programming and building decentralized applications on StarkNet.  

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!   

Looking forward to contributing!

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ShantelPeters** [comment]
Can I be assigned to this?


To solve this issue,
I will  thoroughly review and reconcile the merged PRs with the main branch, then systematically address each identified bug and visual issue, including loading indicators, appbar, text sizing, waiting room updates, animation problems, and overlay scaling, to ensure a polished and fully functional gameplay experience.

**Comment by Jake1698** [comment]
can I try this one pls?

**Comment by Amarjeet325** [comment]
Could I take a shot at this?

**Comment by codeZe-us** [comment]
I will like to work on this

**Comment by mimisavage** [comment]
I’d like to work on this.

**Comment by gianalarcon** [comment]
All yours @Jake1698 . Please test your implementation thoroughly before submitting it for review. We expect your draft PR within the next 24 hours.

**Comment by gianalarcon** [comment]
close with #23
