### ISSUE TITLE
Update `create game` section

### ISSUE THREAD

**Issue by gianalarcon** [Quantum3-Labs/themarquis-app#19]
## Issue Overview

`Create game` section is missing a manual enter token field

## Proposed Solutions or Ideas

- Implement this section based on provided [design](https://www.figma.com/design/bnuIyw9uQSTdWTJ273WUgn/The-Marquis-Mobile-App-Only-Dust?node-id=4554-6476&node-type=canvas&t=4NugNRwW3ZYeNlXZ-0)
![image](https://github.com/user-attachments/assets/31ef22c4-dea7-4e11-bb51-6585aed0212e)

- Make sure integration and previous functionality works

**Comment by davedumto** [comment]
Can I handle this issue?

**Comment by kallis312** [comment]
I'd like to take this issue.

**Comment by Emrys02** [comment]
Hey! @gianalarcon

Can I pick this up? I'd create a draft PR within hours of the UI being available

**Comment by ncoquelet** [comment]
Hey,

I'm a dev with 20 years of XP, super comfy with TypeScript, React/Next, Dapps, Prisma, CI/CD. I ship fast and high-quality stuff. Worked with AFK and GoStarkMe, check my GitHub profile for more details (got several hackathon prizes).
Currently doing Basecamp 11.

Can I jump on this task?

**Comment by Judah04** [comment]
Hey! @gianalarcon

I'd love to do this task.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Jake1698** [comment]
can I try this one pls?

**Comment by Amarjeet325** [comment]
Could I take a shot at this?

**Comment by mimisavage** [comment]
Mind if I try this one?

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by DuendexCR** [comment]
Let me handle this issue!

**Comment by caxtonacollins** [comment]
I am a Full Stack Developer with two years of professional experience, specializing in web3. I have strong background in blockchain and extensive experience in Next.js/React, TypeScript, Cairo and Rust.

I will like to take care of this. Please assign me this issue

**Comment by Shalomnze** [comment]
Hi, I am Nze Shalom, I’ve over 2 years professional experience working on frontend applications (React, Vue, Next, Nuxt, TS) and currently learning cairo. I've gone through the repository and design. I believe this is an excellent first issue for me to contribute to. Can take on this task? ETA is 18hrs

**Comment by gianalarcon** [comment]
All yours @Emrys02 .  Please test your implementation thoroughly before submitting it for review. We expect your draft PR within the next 24 hours. 
Create your own branch based on `develop` branch and send your PR to `develop` branch  as well.
