### ISSUE TITLE
Mobile App: Implement views for in-game section

### ISSUE THREAD

**Issue by gianalarcon** [Quantum3-Labs/themarquis-app#2]
## Issue Overview

1. Current view and flow of in-game section is outdated.
2. Current implementation of share match results is not showing the expected banner and dynamic data.

## Proposed Solutions or Ideas

1. Fix based on provided [design](https://www.figma.com/design/Zwa4tGNPAfPgAkDZtQrNLa/marquis-mobile?node-id=0-1&node-type=canvas&t=Vk06RMlSJqED29zZ-0)
![image](https://github.com/user-attachments/assets/b476fdac-e776-4e70-b95e-d6a9158fbdab)

2. Fix based on provided [design](https://www.figma.com/design/Zwa4tGNPAfPgAkDZtQrNLa/marquis-mobile?node-id=46-14360&node-type=frame&t=Vk06RMlSJqED29zZ-0)
![image](https://github.com/user-attachments/assets/8edbee0c-e7a0-4e95-9b41-b98df52d909c)

**Comment by hoangkianh** [comment]
Can I be assigned to this? i am from starkent.dart group?

**Comment by Supa-mega** [comment]
Could I take a shot at this?

**Comment by gianalarcon** [comment]
Hi @Supa-mega . Any updates on this? We expect at least a draft PR within the upcoming hours. Thanks!

**Comment by gianalarcon** [comment]
Hi @Supa-mega  - Checking in on your progress. Please submit your PR within the next few hours, or we'll need to reassign this issue. Let me know if you're blocked.

**Comment by codeZe-us** [comment]
Flutter Developer.

I can do this, this is understandable. This will take me 1 day(24 hours) to complete.

**Comment by akintewe** [comment]
Hello, I am so happy to have a chance to contribute, i am a flutter developer with 4 years experience and would love to work on this issue. 

Thank you so much for this opportunity :)

My ETA is 48 hours

**Comment by Emrys02** [comment]
Can I take this issue, I have lots of experience building flutter mobile apps. ETA is 48hrs

**Comment by gianalarcon** [comment]
All yours @akintewe.  We expect at least a draft PR within the upcoming hours. Thanks!

**Comment by akintewe** [comment]
Alright thank you, will do

**Comment by gianalarcon** [comment]
Hi @Emrys02 , you can also have a look issue #4

**Comment by gianalarcon** [comment]
closed with #12
