### ISSUE TITLE
Implement `Checkers` : `create game` section

### ISSUE THREAD

**Issue by gianalarcon** [Quantum3-Labs/themarquis-app#20]
## Issue Overview

Implement views of game logic/mechanism for checkers 

## Proposed Solutions or Ideas

- Implement this section based on provided [design](https://www.figma.com/design/bnuIyw9uQSTdWTJ273WUgn/The-Marquis-Mobile-App-Only-Dust?node-id=4554-6476&node-type=canvas&t=82lteI9XrWzdZc9q-0)
 
![image](https://github.com/user-attachments/assets/e9521e6f-d9ba-47c0-9167-8ff5c57dad9c)

- There is no back-end or smart contracts, so no integration need it, Focus on implement and connect views
- This issue focuses on implementing the create game part.
  - CheckersGame (just an empty flame game)
  - CheckersProvider (mock it for now without backend functions)
  - Create Game Overlay
  - Other related components (join game dialog, join session dialog, etc.)

**Comment by wms2537** [comment]
Gameplay should be implemented in flame. Here's a list of components we might need:
- CheckersGame (main flame game)
- CheckersProvider (mock it for now without backend functions)
- CheckersBoard 
- CheckersPin
- UserStatsComponent

Overlays and game state management similar to existing Ludo game.

**Comment by Hoossayn** [comment]
Hi, can i take on this issue?.  Already familiar with the codebase and the flow of the Ludo game

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

I have already been a contributor to this project on one of the previous odhacks

**Comment by Judah04** [comment]
Hi @gianalarcon , I'd love to work on implementing this design.

**Comment by ncoquelet** [comment]
Hey,

I'm a dev with 20 years of XP, super comfy with TypeScript, React/Next, Dapps, Prisma, CI/CD. I ship fast and high-quality stuff. Worked with AFK and GoStarkMe, check my GitHub profile for more details (got several hackathon prizes).
Currently doing Basecamp 11.

Can I contribute to this one?

**Comment by akintewe** [comment]
Hello i am a flutter developer and would love to work on this section of  the app i am ver familiar with the codebase and would love to work more on it ;) ETA 48 hours

**Comment by mimisavage** [comment]
Can I handle this task?

**Comment by akintewe** [comment]
Hello i am a flutter developer and would like to work on this issue once more, thank you for this opportunity :) ETA 48 hours

**Comment by caxtonacollins** [comment]
please assign me this issue, am proficient in design comversion and ready to put in the work.. 48 hours

**Comment by Supa-mega** [comment]
Is it okay if I tackle this?

**Comment by ONEONUORA** [comment]
May I handle this issue? I am a full stack and blockchain developer. ETA 24 hours

**Comment by Jagadeeshftw** [comment]
Hi,
I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Hi,  

I’d be thrilled to work on this issue as I have extensive experience with Cairo programming and building decentralized applications on StarkNet.  

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!   

Looking forward to contributing!

**Comment by 1nonlypiece** [comment]
Could I grab this task?Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by Emrys02** [comment]
### Hey! @gianalarcon  can I pick this?

I've been previously exposed to the codebase hence getting started wouldn't be an issue. 

I worked on a similar implementation for the ***Ludo Game*** during the previous hackathon and can complete this quickly.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ShantelPeters** [comment]
I'd love to work on this!

To solve this issue,
I will  implement the create game feature for checkers by setting up the necessary frontend components, including CheckersGame, CheckersProvider (mocked without backend functions), Create Game Overlay, and other related components, based on the provided design image, without integrating any backend or smart contracts.

**Comment by Amarjeet325** [comment]
Can I try solving this issue?

**Comment by codeZe-us** [comment]
I can get this done.

**Comment by DuendexCR** [comment]
Can I attempt this issue?

**Comment by therealemino** [comment]
I'd like to take this issue.

**Comment by gianalarcon** [comment]
All yours @codeZe-us  .  Please test your implementation thoroughly before submitting it for review. We expect your draft PR within the next 24 hours. 
Create your own branch based on `develop` branch and send your PR to `develop` branch  as well.
