### ISSUE TITLE
Implement `Checkers` : `game-play` section

### ISSUE THREAD

**Issue by gianalarcon** [Quantum3-Labs/themarquis-app#21]
## Issue Overview

Implement views of game logic/mechanism for checkers 

## Proposed Solutions or Ideas

- Implement this section based on provided [design](https://www.figma.com/design/bnuIyw9uQSTdWTJ273WUgn/The-Marquis-Mobile-App-Only-Dust?node-id=4554-6476&node-type=canvas&t=82lteI9XrWzdZc9q-0)
 
![image](https://github.com/user-attachments/assets/561150b3-64db-4a25-b42d-a8af207aa23c)

- There is no back-end or smart contracts, so no integration need it, Focus on implement and connect views
- This issue focuses on implementing the game play part.
  - CheckersGame (flame game wiring up all the components)
  - CheckersBoard Component
  - CheckersPin Component
  - UserStats Component
  - and other components that make up the game

**Comment by Supa-mega** [comment]
I’d like to work on this.

**Comment by abdegenius** [comment]
I'd like to handle this task.

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

I have already been a contributor to this project on one of the previous odhacks

**Comment by caxtonacollins** [comment]
I am a Full Stack Developer with two years of professional experience, specializing in web3. I have strong background in blockchain and extensive experience in Next.js/React, TypeScript, Cairo and Rust.

I will like to take care of this.
this will be my first time contributing to this project

**Comment by codeZe-us** [comment]
Please can I take on this task?

**Comment by mimisavage** [comment]
Is it okay if I take this?

**Comment by codeZe-us** [comment]
Please can I take on this task?

**Comment by ONEONUORA** [comment]
Mind if I try this one? I am a full stack and blockchain developer. ETA 24 hours

**Comment by Jagadeeshftw** [comment]
Hi,
I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Hi,  

I’d be thrilled to work on this issue as I have extensive experience with Cairo programming and building decentralized applications on StarkNet.  

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!   

Looking forward to contributing!

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ShantelPeters** [comment]
Can I take care of this issue?

To approach this process,  I will implement the frontend views of the checkers game mechanism by wiring up the necessary components, including CheckersGame, CheckersBoard, CheckersPin, UserStats, and other relevant components, based on the provided design image, focusing solely on the client-side implementation without any backend or smart contract integration.


This is my first time contributing to this ecosystem

**Comment by Amarjeet325** [comment]
Can I take this from here?

**Comment by Jemiiah** [comment]
Hello Jeremiah I'm a frontend developer in web3 I have contributed to previous OD hacks. i have made over 85+ contribution in past OD Hacks Here's my OD Hack profile: https://app.onlydust.com/Jemiiah I intend to solving this issue with an ETA of 48 hours

**Comment by obah** [comment]
Hi, I am Obaloluwa, a frontend developer with over 2 years of experience, using React, NextJs, typescript and tailwindCSS regularly and I am well familiar with creating pages like the one in this task.

Can I work on this issue?

My plan to handle this issue:
1. I will study the design to know all the requirements and components I need to create, then familarize myself with the code base to get the structure and tools used.
2. Next is I will create all the required ui components for this screen, ensuring they are resuable, responsive, accessible and match the design perfectly.
3. Then, implement the screen for this task, ensure its functional and all the issues tackled.

ETA: 1 to 2 days.

I will be sure to communicate with the team on telegram if I face any blockers and would create a PR once I am done.

**Comment by DuendexCR** [comment]
May I take care of this?

**Comment by davedumto** [comment]
Hi, I'm David, a new open-source contributor, proficient in TypeScript, JavaScript, Tailwind CSS, and ShadCN. I can help implement the game views for checkers by:

Implementing the CheckersGame component to wire up all game elements.
Developing the CheckersBoard, CheckersPin, and UserStats components.
Connecting and styling other components as required to create a seamless gameplay experience.
ETA 3 days

**Comment by od-hunter** [comment]
Hi, please can I be assigned this please? I would love to be the given the opportunity to solve this issue please. I have experience in html, css, JavaScript, TypeScript and cairo.

I'll make sure I follow the design provided and I won't waste time this time around please.
Kindly assign me please I'm up for the task.

**Comment by Dorcas18** [comment]
Could I take a shot at this?

**Comment by akintewe** [comment]
Hello can i work on this please my ETA is 48 hours thank you

**Comment by gianalarcon** [comment]
All yours @akintewe   Please you will need to wait until issue #20 is solved, after that you can start working. I will notify you. Thanks!

**Comment by akintewe** [comment]
> All yours @akintewe Please you will need to wait until issue #20 is solved, after that you can start working. I will notify you. Thanks!

Ok thank youuu

**Comment by gianalarcon** [comment]
closed with #27
