### ISSUE TITLE
Implement `Checkers` : `winning overlays` section

### ISSUE THREAD

**Issue by gianalarcon** [Quantum3-Labs/themarquis-app#22]
## Issue Overview

Implement views of game logic/mechanism for checkers 

## Proposed Solutions or Ideas

- Implement this section based on provided [design](https://www.figma.com/design/bnuIyw9uQSTdWTJ273WUgn/The-Marquis-Mobile-App-Only-Dust?node-id=4554-6476&node-type=canvas&t=82lteI9XrWzdZc9q-0)
 
![image](https://github.com/user-attachments/assets/61c212f7-04f1-44bd-b65e-ae940b263245)

- There is no back-end or smart contracts, so no integration need it, Focus on implement and connect views
- This issue focuses on implementing the create game part.
  - GameWinOverlay
  - Overlays and game state management similar to existing Ludo game.
  - Test whole game flow (create game, gameplay, winning) views on different device sizes. Fix overflows.
    - Suggest to use adaptive scaling.

**Comment by Supa-mega** [comment]
Can I take care of this issue?

**Comment by abdegenius** [comment]
Could I be assigned to this?

**Comment by zintarh** [comment]
Can I take this from here?

To handle the **Create Game** view and **GameWinOverlay**, I would convert the design into UI components in React, ensuring proper state management using React’s state or context to control the game flow, including creation and completion states. The **GameWinOverlay** would be displayed conditionally based on the game state, providing a seamless transition from gameplay to the win screen, similar to the existing Ludo game experience.

**Comment by caxtonacollins** [comment]
Could I grab this task?

**Comment by Hoossayn** [comment]
Hi, can i work on this 

## How will i implement this 
- create a custom dialog 
- properly manage state for win or loose situation

**Comment by mimisavage** [comment]
I'd like to take this issue.

**Comment by Hoossayn** [comment]
Hi, can i work on this? .

## How I Intent to go about this
- create a custom dialog 
- manage state for both winning and loosing 
- Add necessary elevation where needed

**Comment by codeZe-us** [comment]
Can I take this issue?

**Comment by ONEONUORA** [comment]
Can I take this issue? I am a full stack and blockchain developer. ETA 24 hours

**Comment by jedstroke** [comment]
Is it okay if I take this?

**Comment by Jagadeeshftw** [comment]
Hi,
I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Hi,  

I’d be thrilled to work on this issue as I have extensive experience with Cairo programming and building decentralized applications on StarkNet.  

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!   

Looking forward to contributing!

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ShantelPeters** [comment]
Could I try solving this?

To approach this issue,  I will focus on implementing the frontend views of the checkers game logic, connecting them to manage game state, and creating a game overlay similar to the existing Ludo game, without integrating any backend or smart contracts.

**Comment by akintewe** [comment]
I would love to work on this issue , i have experience in flutter and would love to be given the opportunity to work on this again. ETA 12 hours

**Comment by Amarjeet325** [comment]
Can I take this from here?

**Comment by Michaelkingsdev** [comment]
Could I try solving this?

**Comment by obah** [comment]
Hi, I am Obaloluwa, a frontend developer with over 2 years of experience, using React, NextJs, typescript and tailwindCSS regularly and I am well familiar with creating pages like the one in this task.

Can I work on this issue?

My plan to handle this issue:
1. I will study the design to know all the requirements and components I need to create, then familarize myself with the code base to get the structure and tools used.
2. Next is I will create all the required ui components for this screen, ensuring they are resuable, responsive, accessible and match the design perfectly.
3. Then, implement the screen for this task, ensure its functional and all the issues tackled.

ETA: 1 to 2 days.

I will be sure to communicate with the team on telegram if I face any blockers and would create a PR once I am done.

**Comment by DuendexCR** [comment]
Can I contribute to this one?

**Comment by od-hunter** [comment]
Hi, please can I be assigned this please? I would love to be the given the opportunity to solve this issue please. I have experience in html, css, JavaScript, TypeScript and cairo.

I'll make sure I follow the design provided and I won't waste time this time around please.
Kindly assign me please I'm up for the task.

**Comment by caxtonacollins** [comment]
I am a Full Stack Developer with two years of professional experience, specializing in web3. I have strong background in blockchain and extensive experience in Next.js/React, TypeScript, Cairo and Rust.

I will like to take care of this.

**Comment by Shalomnze** [comment]
Hi, I am Nze Shalom, I’ve over 2 years professional experience working on frontend applications (React, Vue, Next, Nuxt, TS) and currently learning cairo. I've gone through the repository and design. I believe this is an excellent first issue for me to contribute to. Can take on this task? ETA is 12hrs

**Comment by Dorcas18** [comment]
Can I attempt this issue?

**Comment by gianalarcon** [comment]
All yours @Hoossayn   Please you will need to wait until issue #20 is solved, after that you can start working. I will notify you

**Comment by gianalarcon** [comment]
closed with #29
