### ISSUE TITLE
Mobile App: Use starknet.dart SDK

### ISSUE THREAD

**Issue by gianalarcon** [Quantum3-Labs/themarquis-app#3]
## Issue Overview

Currently we don't import any functionality from starknet.dart. 

## Proposed Solutions or Ideas

- Implement a call method to read ETH and STRK Balance. [starknet.dart Reference](https://starknetdart.dev/packages/starknet-provider) 

- The idea is that you will show this user STRK balance based on his wallet address. 
![image](https://github.com/user-attachments/assets/4aa6dc54-01ff-4b3c-be85-d025370f609a)

- You can create a dummy icon to show his ETH Balance as well

**Comment by mexes20** [comment]
May I pick this up? I have three years experience in Software development and have contributed to some projects on OD here.

ETA: 10 hours.

**Comment by Supa-mega** [comment]
Could I try solving this?

**Comment by Hoossayn** [comment]
I'll like to handle this one

**Comment by ShantelPeters** [comment]
May I handle this issue?

**Comment by JoE11-y** [comment]
Is this issue still available?

**Comment by gianalarcon** [comment]
All yours @JoE11-y Remember that you have to create your branch based on our develop branch and your PR should point to our develop branch. Not to our main branch

**Comment by JoE11-y** [comment]
Thank you @gianalarcon.

Will do that 💪

**Comment by gianalarcon** [comment]
@JoE11-y Any updates on this? We expect at least a draft PR in the upcoming hours. Thanks!

**Comment by JoE11-y** [comment]
Alright @gianalarcon.

Will send in the draft.

**Comment by gianalarcon** [comment]
Hi @JoE11-y . Checking in on your progress. Please submit your PR within the next few hours. Let me know if you're blocked.

**Comment by JoE11-y** [comment]
Thank you Gian.

Please check discord having issues with the referral ID.

**Comment by gianalarcon** [comment]
Closed with #7
