### ISSUE TITLE
Mobile App: Implement views for Pre-Game section

### ISSUE THREAD

**Issue by gianalarcon** [Quantum3-Labs/themarquis-app#4]
## Issue Overview

Current view and flow of Pre-Game is outdated

## Proposed Solutions or Ideas

Implement/Update views for Pre-Game section. [here](https://www.figma.com/design/Zwa4tGNPAfPgAkDZtQrNLa/marquis-mobile?node-id=0-1&node-type=canvas&t=Vk06RMlSJqED29zZ-0). New UI implementation shouldn't break current functionality
![image](https://github.com/user-attachments/assets/6e9ef1df-c70f-43e9-8664-4049d27bbb2a)

Note: Currently the server doesn't support 2 players, we need 4 players to start the game. Anyway we will need the UI/layout for 2 players.

**Comment by IdrisAdeyemi01** [comment]
I'm interested in this

**Comment by IdrisAdeyemi01** [comment]
Can I take this from here?

**Comment by Supa-mega** [comment]
Could I be assigned to this?

**Comment by gianalarcon** [comment]
Hi @IdrisAdeyemi01 . Any updates on this? We expect at least a draft PR within the upcoming hours. Thanks!

**Comment by IdrisAdeyemi01** [comment]
Yes @gianalarcon, I'll make a draft PR very soon. Thanks.

**Comment by gianalarcon** [comment]
Hi @IdrisAdeyemi01. Checking in on your progress. Please submit your PR within the next few hours. Let me know if you're blocked.

**Comment by IdrisAdeyemi01** [comment]
Hi @gianalarcon, my weekend became unexpectedly hectic due to some activities. I've loaded the app now and ready to start implementation. I'll send you a draft PR in a couple of hours from now. I'll also let you know if I encounter any issues.
Thanks

**Comment by IdrisAdeyemi01** [comment]
Is there a test email?
Or do you have we have a test referral code to sign up with?

**Comment by gianalarcon** [comment]
You can use any of these ref code
J51QECW1
JJ6TFGNW
for further questions you can join to our [discord](https://discord.gg/AgbJ9gDq)

**Comment by petersdt** [comment]
May I pick this up?

am a frontend developer with experience in developing web based applications using js and js framework. kindly assign me this task

**Comment by Luluameh** [comment]
"Hi  @themarquis-app,
I’d love to work on this issue! I’ve reviewed the requirements and have a clear plan to implement the updated Pre-Game UI while ensuring the current functionality remains intact. Additionally, I’ll ensure the layout accommodates both 2-player and 4-player scenarios as outlined if needed.  I can deliver this solution within the next 24-48 hours. Please let me know if I can get started!"

**Comment by Agbeleshe** [comment]
Hello, I would love to be assigned this issue. I have experience working on numerous UI designs similar to this one and am confident I can complete this design within a day.

**Comment by mimisavage** [comment]
Let me handle this issue!

**Comment by aniruddhaaps** [comment]
I would update the Pre-Game UI with these designs, ensuring consistent flow while creating, joining, and finding games. Maintain backward compatibility with the current functionality.
Implement 2-player and 4-player mode UI, assuming the server just supports 4 players, to ensure it's not a future problem with the app.
The new UI should be tested thoroughly, ensuring seamless integration and adequate functionality of all pre-game features.

**Comment by Emrys02** [comment]
@gianalarcon I'm getting started with this as instructed

**Comment by gianalarcon** [comment]
closed with #13
