### ISSUE TITLE
Mobile App: Implement waiting room

### ISSUE THREAD

**Issue by gianalarcon** [Quantum3-Labs/themarquis-app#5]
Issue Overview

Current view and flow of waiting room is outdated.

## Proposed Solutions or Ideas

1. Implement waiting room for 4 players. Design [here](https://www.figma.com/design/Zwa4tGNPAfPgAkDZtQrNLa/marquis-mobile?node-id=0-1&node-type=canvas&t=Vk06RMlSJqED29zZ-0)
![image](https://github.com/user-attachments/assets/7223b270-78d6-4476-a3ea-821a1e09c807)

2. Implement waiting room for 2 players. Design [here](https://www.figma.com/design/Zwa4tGNPAfPgAkDZtQrNLa/marquis-mobile?node-id=0-1&node-type=canvas&t=Vk06RMlSJqED29zZ-0) 
![image](https://github.com/user-attachments/assets/a71e74b8-38b6-4c6b-b560-95098782f3a3)

Note: Currently the server doesn't support 2 players, we need 4 players to start the game. Anyway we will need the UI/layout for 2 players.

**Comment by hoangkianh** [comment]
Can I handle this task? I'm from the starknet.dart chat :)

**Comment by Supa-mega** [comment]
I'd like to take this issue.

**Comment by gianalarcon** [comment]
Hi @hoangkianh. Any updates on this? We expect at least a draft PR within the upcoming hours. Thanks!

**Comment by gianalarcon** [comment]
Hi @hoangkianh   - Checking in on your progress. Please submit your PR within the next few hours, or we'll need to reassign this issue. Let me know if you're blocked.

**Comment by hoangkianh** [comment]
hi @gianalarcon.  Sorry for late response, I’m usually not online on weekends so i cant reply you in time. everything is ok, i got the app up and running and can continue working tomorrow. can you reassign it for me?

**Comment by codeZe-us** [comment]
Flutter Developer.

I can do this, this won't take much time. Will deliver in 5 hours if assigned.

**Comment by akintewe** [comment]
Hello, I am so happy to have a chance to contribute, i am a flutter developer with 4 years experience and would love to work on this issue. 

Thank you so much for this opportunity :)

My ETA is 24 hours

**Comment by Emrys02** [comment]
Can I take this issue, I have lots of experience building flutter apps and can easily utilize it in implementing a dynamic UI which would work perfectly for both the 4 players and 2 players views

**Comment by Emrys02** [comment]
Can I take this issue, I have lots of experience building flutter apps and can easily utilize it in implementing a dynamic UI which would work perfectly for both the 4 players and 2 players views. ETA is 24hrs.

**Comment by gianalarcon** [comment]
All yours @codeZe-us . We expect at least a draft PR within the upcoming hours. Thanks!

**Comment by gianalarcon** [comment]
Hi @Emrys02 if you interested you can try issue #8

**Comment by Emrys02** [comment]
Sure @gianalarcon , I'll check it out

**Comment by codeZe-us** [comment]
> All yours @codeZe-us . We expect at least a draft PR within the upcoming hours. Thanks!

Yeah, sure. Will start right away.

**Comment by codeZe-us** [comment]
> All yours @codeZe-us . We expect at least a draft PR within the upcoming hours. Thanks!

@gianalarcon please what is the referral code?

**Comment by wms2537** [comment]
You can get the referral code in the discord channel @codeZe-us

**Comment by gianalarcon** [comment]
closed with #14
