### ISSUE TITLE
Mobile App: Explore starknet.dart SDK 

### ISSUE THREAD

**Issue by gianalarcon** [Quantum3-Labs/themarquis-app#8]
## Issue Overview - Current state

- Limited usage of `starknet.dart` package, primarily for balance checking, on[ starknet-dart](https://github.com/The-Marquis-Gaming/themarquis-app/tree/starknet-dart) branch
- API endpoints handle core game functionality like session `create-session` and `join-session`

## Proposed Solutions or Ideas

1.Replace API endpoint with smart contract call/invoke. Implement [create_session](https://github.com/The-Marquis-Gaming/themarquis-ui-sc/blob/ab9b65520deedadef766617ead2a1a97c462f084/packages/snfoundry/contracts/src/interfaces/IMarquisGame.cairo#L117) smart contract integration
2.  Implement [join_session](https://github.com/The-Marquis-Gaming/themarquis-ui-sc/blob/ab9b65520deedadef766617ead2a1a97c462f084/packages/snfoundry/contracts/src/interfaces/IMarquisGame.cairo#L121) smart contract integration
3. Write tests for new functionality

Note: Your PR should point to `starknet-dart` branch

**Comment by wms2537** [comment]
I think we have to first decide on the wallet handling strategy. Since now we are handling the wallet on the API side. We have the following options:
1. Make it non-custodial, users manage the wallet locally, create one during signup or import one and then the details stored encrypted on device, with options to export private key & mnemonics. Some additional concerns includes backend side might have to add methods to get the user details, how to manage the username, etc.
2. Make it custodial, use encrypted methods to get the keys during login.
3. Use existing wallets (require connection to existing starknet wallets, such as Argent Mobile).

**Comment by chigozzdevv** [comment]
Hello, please can take up this issue?

**Comment by CEOliam** [comment]
I'd like to handle this task.

**Comment by MrRoudyk** [comment]
Could I take a shot at this?

**Comment by mimisavage** [comment]
I’d like to resolve this.

**Comment by Supa-mega** [comment]
May I pick this up?

**Comment by aniruddhaaps** [comment]
Issue Overview - Current state
Lack of wide usage of starknet.dart package - mainly for balance checking
API endpoints handle core game functionality like session create-session and join-session
So, I would do
1.Replace API endpoint with smart contract call/invoke. Add create_session smart contract integration
2. Add join_session smart contract integration
3. Add tests for new functionality

**Comment by onchezz** [comment]
I’d like to work on this.

**Comment by baitcode** [comment]
I'd like to handle this task.

**Comment by 0xdevcollins** [comment]
Could I be assigned to this?

**Comment by Michaelkingsdev** [comment]
Can I take this issue?

**Comment by 7-falseparfait** [comment]
I'd love to work on this!

**Comment by tasneemtoolba** [comment]
Can I jump on this task? I was a Flutter developer for over 2 years, and recently shifted to web3

**Comment by gianalarcon** [comment]
@tasneemtoolba be aware that the OD will end soon, I will give it to you to anyway. Let me know if you change your mind.
Check that the scope of this issue is what I described

> ## Issue Overview - Current state
> * Limited usage of `starknet.dart` package, primarily for balance checking, on[ starknet-dart](https://github.com/The-Marquis-Gaming/themarquis-app/tree/starknet-dart) branch
> * API endpoints handle core game functionality like session `create-session` and `join-session`
> 
> ## Proposed Solutions or Ideas
> 1.Replace API endpoint with smart contract call/invoke. Implement [create_session](https://github.com/The-Marquis-Gaming/themarquis-ui-sc/blob/ab9b65520deedadef766617ead2a1a97c462f084/packages/snfoundry/contracts/src/interfaces/IMarquisGame.cairo#L117) smart contract integration 2. Implement [join_session](https://github.com/The-Marquis-Gaming/themarquis-ui-sc/blob/ab9b65520deedadef766617ead2a1a97c462f084/packages/snfoundry/contracts/src/interfaces/IMarquisGame.cairo#L121) smart contract integration 3. Write tests for new functionality
> 
> Note: Your PR should point to `starknet-dart` branch

**Comment by tasneemtoolba** [comment]
@gianalarcon so I managed to get almost everything but the required variable `contractAddress` in `FunctionCall`, so the following is what I have for the `createSession` function
```dart
final response = await provider.call(
        request: FunctionCall(
          contractAddress: ethContractAddress,
          entryPointSelector: getSelectorByName('create_session'),
          calldata: [token, amountFelt],
        ),
        blockId: const BlockId.blockTag("latest"),
      );
```
same with `joinSession`
but yea I'm not sure what to put in `contractAddress`, this is one thing, another thing is that there's no third parameter for `color` in the Cairo function interface, but there's variable `color` in both `createSession` and `joinSession` in the flutter app

besides, how can I test it without logging in? I get an error when I login, the error: 
```
An Error Occurred!
ClientException with SocketException:
Failed host lookup: 'api.themarquis.xyz'
(OS Error: No address associated with
hostname, errno = 7), uri=https://
api.themarquis.xyz/auth/signup
```

**Comment by gianalarcon** [comment]
Hi @tasneemtoolba 
Make sure you working on[ starknet-dart](https://github.com/The-Marquis-Gaming/themarquis-app/tree/starknet-dart) branch

The all system have two smart contracts deployed

MARQUIS_CONTRACT_ADDRESS="0x5cc54532067b18dfc07f409b964daae28a88f761e57641fbe5c9984e5bb4add"
LUDO_CONTRACT_ADDRESS="0x47c09d9acf59d1be1151edb2035e2a41de5291a28637ab3b14087e85382d212"

1. You can find the contracts details [here](https://github.com/The-Marquis-Gaming/themarquis-ui-sc/tree/main/packages/snfoundry/contracts/src) 

2. Yes, we use color for the API/backend side, but the cairo contracts dont have this input parameter, so you dont need to pass `color` in that case

3. In order to interact with the API, You need to always login, you can use the [sandbox sign-up/login](https://api.themarquis.xyz/api-v1/#/Auth/signup_sandbox) for fast development

For further questions, you can create a draft PR and/or join to our discord for support https://discord.gg/AgbJ9gDq
