### ISSUE TITLE
Mobile App: Wallet Handling Strategies

### ISSUE THREAD

**Issue by wms2537** [Quantum3-Labs/themarquis-app#9]
I think we have to first decide on the wallet handling strategy before we look more into using starknet.dart #8. Since now we are handling the wallet on the API side. We have the following options:

1. Make it non-custodial, users manage the wallet locally, create one during signup or import one and then the details stored encrypted on device, with options to export private key & mnemonics. Some additional concerns includes backend side might have to add methods to get the user details, how to manage the username, etc.
2. Make it custodial, use encrypted methods to get the keys during login.
3. Use existing wallets (require connection to existing starknet wallets, such as Argent Mobile).

**Comment by JoE11-y** [comment]
Would love to take this on. 💪

**Comment by wms2537** [comment]
@JoE11-y May I know which option you will be trying out?

**Comment by JoE11-y** [comment]
@wms2537  I'm actually leaning towards 3.

**Comment by wms2537** [comment]
From what I know this option might require some discussions with Argent Team on coming out with a protocol to communicate with the Argent mobile wallet. WalletConnect Support seems limited, but you can also try it out anyways.

However a new problem arises, since every roll dice and play move requires the user to call the contract, if we redirect users to another app to approve the transaction this will highly affect the gameplay experience.

**Comment by JoE11-y** [comment]
Oh yeah that will be a bad UX.
Then maybe sticking to 2 might be the best way to go.

**Comment by wms2537** [comment]
Thinking about 1, probably we can make something like this [https://github.com/cartridge-gg/controller/tree/main](https://github.com/cartridge-gg/controller/tree/main)

**Comment by JoE11-y** [comment]
GM. 
Do you mean integrating it?
Or making a flutter replica?

**Comment by wms2537** [comment]
Make a flutter replica

**Comment by JoE11-y** [comment]
Ooh I like the sound of that. 😁

**Comment by wms2537** [comment]
But anyways we can explore option 1 first, option 2 will be the fallback approach, option 3 will only be feasible if we can sign only one transaction for the whole game

**Comment by onchezz** [comment]
Id also love to take help out on this

**Comment by JoE11-y** [comment]
@wms2537 did some research and I think the starknet wallet kit should be able to help us achieve 1.

https://github.com/focustree/starknet.dart/tree/main/packages/wallet_kit

**Comment by wms2537** [comment]
Can give it a try, but have to confirm the Cairo versions supported by that package.
